ALTER TABLE meeting_minutes 
ADD COLUMN IF NOT EXISTS model TEXT DEFAULT 'gemini-3.6-flash',
ADD COLUMN IF NOT EXISTS input_tokens INT DEFAULT 0,
ADD COLUMN IF NOT EXISTS output_tokens INT DEFAULT 0,
ADD COLUMN IF NOT EXISTS total_tokens INT DEFAULT 0,
ADD COLUMN IF NOT EXISTS estimated_cost_inr NUMERIC(10,4) DEFAULT 0,
ADD COLUMN IF NOT EXISTS estimated_cost_usd NUMERIC(10,6) DEFAULT 0;

ALTER TABLE meeting_minutes_versions 
ADD COLUMN IF NOT EXISTS model TEXT DEFAULT 'gemini-3.6-flash',
ADD COLUMN IF NOT EXISTS input_tokens INT DEFAULT 0,
ADD COLUMN IF NOT EXISTS output_tokens INT DEFAULT 0,
ADD COLUMN IF NOT EXISTS total_tokens INT DEFAULT 0,
ADD COLUMN IF NOT EXISTS estimated_cost_inr NUMERIC(10,4) DEFAULT 0,
ADD COLUMN IF NOT EXISTS estimated_cost_usd NUMERIC(10,6) DEFAULT 0;
